Accounts-handling services
shinonome-inc/backend-final-assignment-Fujioka_backend pull request #1
Opened 2022-06-02 04:59 UTC by fujinomoto62

sign-up, logout, login.

2022-06-02 06:14 UTC, Akinori13 requested changes
よくできています
- 最終行は空行を挿入してください。
- このPRに関係ないコードは削除してください。
- pycacheが含まれています。gitの管理対象外にしてください。
- 要求のテストを記載してください。最終課題テスト項目要件整理参照

2022-06-02 06:14 UTC, Akinori13 commented on accounts/admin.py
> +admin.site.register(User, CustomUserAdmin)
最終行に空行を挿入してください

2022-06-02 06:14 UTC, Akinori13 commented on accounts/admin.py
> +    # fieldsets = User.fieldsets + ((None, {'fields': ('following', 'following_number')}),)
今回のPRに関係ない不要なコメントアウトは削除する。

2022-06-02 06:14 UTC, Akinori13 commented on accounts/models.py
> +class User(AbstractUser):
今回のPRに関連するコードだけ残してください

2022-06-02 06:14 UTC, Akinori13 commented on accounts/models.py
> +# class User(AbstractBaseUser, PermissionsMixin):
不要なコードは削除します

2022-06-02 06:14 UTC, Akinori13 commented on welcome/views.py
> +def signupfunc(request):
UserCreationFormを使ってください。またサインアップ機能はaccountsアプリに作成してください

2022-06-02 08:47 UTC, fujinomoto62 commented on accounts/admin.py
> +admin.site.register(User, CustomUserAdmin)
本PRと関係のあるファイル全てにて最終行に空行を入れました。

2022-06-02 08:49 UTC, fujinomoto62 commented on accounts/models.py
> +# class User(AbstractBaseUser, PermissionsMixin):
本PRと関係のない箇所をすべて削除しました。

2022-06-02 08:51 UTC, fujinomoto62 commented on welcome/views.py
> +def signupfunc(request):
accounts/form.pyにてUserCreateFormを継承する形でこれを用いました。
また、スタイルはFromを用いないものを想定して作成したため、UserCreateFormにより作成しているsingup.htmlに関しては適応しておりません。

2022-06-03 05:22 UTC, Akinori13 requested changes
細部まで気を払ってかけていてよいです！！以下必ず実施してください
- testを書いてください
- gitignoreを書いてください。pycacheとdb.sqlite3などはgitの管理対象外です

2022-06-03 05:22 UTC, Akinori13 commented on tweets/models.py
> +
最終行

2022-06-03 05:22 UTC, Akinori13 commented on tweets/urls.py
> +    path('test/', TemplateView.as_view(template_name='tweets/test.html'), name='test'),
必要ないなら消しちゃってください

2022-06-03 05:22 UTC, Akinori13 commented on accounts/views.py
> +
必要ない空白行は消してください

2022-06-03 05:22 UTC, Akinori13 commented on accounts/models.py
> +    follower_number = models.IntegerField(null=True, blank=True, default=0)
今回のPRに関係ないので消してください

2022-06-03 05:22 UTC, Akinori13 commented on accounts/views.py
> +        form = UserCreationForm()
```suggestion
        form = CreateForm()

```

2022-06-04 07:57 UTC, fujinomoto62 commented on tweets/urls.py
> +    path('test/', TemplateView.as_view(template_name='tweets/test.html'), name='test'),
該当箇所のコメントアウトを削除しました。

2022-06-04 07:59 UTC, fujinomoto62 commented on accounts/models.py
> +    follower_number = models.IntegerField(null=True, blank=True, default=0)
該当箇所を削除しました。

2022-06-04 07:59 UTC, fujinomoto62 commented on accounts/views.py
> +
該当箇所の空行を削除しました。同様に不必要な空行を削除しました。

2022-06-04 08:00 UTC, fujinomoto62 commented on accounts/views.py
> +        form = UserCreationForm()
該当箇所を修正しました。

2022-06-07 06:54 UTC, Akinori13 commented on welcome/tests.py
> +
空行挿入

2022-06-09 03:40 UTC, Akinori13 requested changes
いくつかコメントしました。
gitignore関連はありがとうございました。

2022-06-09 03:40 UTC, Akinori13 commented on welcome/tests.py
> +
空行挿入

2022-06-09 03:40 UTC, Akinori13 commented on welcome/views.py
> +def loginfunc(request):
accountsへ

2022-06-09 03:40 UTC, Akinori13 commented on welcome/views.py
> +@login_required
accountsへ

2022-06-09 03:40 UTC, Akinori13 commented on welcome/views.py
> +def signupfunc(request):
トップページの作成

2022-06-09 03:40 UTC, Akinori13 commented on welcome/tests.py
> +class TestSignUpView(TestCase):
testはaccountsへ

2022-06-09 03:40 UTC, Akinori13 commented on tweets/models.py
> +        return self.text[:7]
このPRに関係ないものを入れない

2022-06-09 03:40 UTC, Akinori13 commented on accounts/tests.py
>      def test_failure_post_with_empty_form(self):
異常系テストでは、データが登録されていないことも確認する

2022-06-09 03:40 UTC, Akinori13 commented on accounts/tests.py
> +        self.assertTrue(form.errors)
エラー内容の確認

2022-06-09 03:40 UTC, Akinori13 commented on accounts/tests.py
> +        self.assertTrue(form.errors)
これをしないと、他の項目でエラーになっている可能性を排除できないから

2022-06-09 03:40 UTC, Akinori13 commented on welcome/views.py
> +def loginfunc(request):
auth_views.LoginViewを使う

2022-06-09 03:40 UTC, Akinori13 commented on welcome/views.py
> +@login_required
auth_views.LogoutViewを使う

2022-06-09 03:40 UTC, Akinori13 commented on accounts/tests.py
>  class TestSignUpView(TestCase):
loginとlogoutのテストの追加

2022-06-09 03:40 UTC, Akinori13 commented on accounts/tests.py
>  class TestSignUpView(TestCase):
下で定義している

2022-06-13 12:04 UTC, fujinomoto62 commented on welcome/views.py
> +def signupfunc(request):
welcome pageを作成しました。

2022-06-13 12:05 UTC, fujinomoto62 commented on welcome/tests.py
> +class TestSignUpView(TestCase):
login/logoutのtestをaccounts/test.pyにて作成しました。

2022-06-13 12:05 UTC, fujinomoto62 commented on accounts/tests.py
>      def test_failure_post_with_empty_form(self):
該当箇所を修正しました。

2022-06-13 12:06 UTC, fujinomoto62 commented on accounts/tests.py
> +        self.assertTrue(form.errors)
該当箇所を修正しました。

2022-06-14 07:22 UTC, Akinori13 requested changes
いくつかコメントしました

2022-06-16 03:18 UTC, fujinomoto62 commented on accounts/templates/accounts/base.html
> +</html>
空行を挿入しました。

2022-06-16 03:19 UTC, fujinomoto62 commented on welcome/static/welcome/welcome.css
> +}
本ファイル及び、加筆を加えた全てのファイルにおいて空行を確認しました。
並びに、本機能と関係ないhtmlファイルがブランチに残っていたため削除しました。

2022-06-16 03:25 UTC, fujinomoto62 commented on accounts/tests.py
>      def test_success_post(self):
私の技術不足より、loginにおいてセッションの確認による有効なlogin状態の確認の術が見つかりませんでした。
代替として、ログイン状態でないとアクセスできないようになっているリダイレクト先への正常なアクセスを確認することより,
間接的にアクセス状態を確認しています。

2022-06-18 03:23 UTC, Akinori13 requested changes
コメントしました

2022-06-18 03:23 UTC, Akinori13 commented on accounts/tests.py
>      def test_success_post(self):
SESSION_KEYはdjango.contrib.authから取得してください

2022-06-18 03:23 UTC, Akinori13 commented on accounts/tests.py
>      def test_success_post(self):
self.client.sessionにSESSION_KEYが含まれるか確認してください

2022-06-23 05:14 UTC, fujinomoto62 commented on tweets/views.py
> +
失礼ながら、該当ファイルの最終行は既に一行空いていると思われます。今一度ご確認ください。

2022-06-23 05:16 UTC, fujinomoto62 reviewed
ログイン状態を確認するためのsession keyの有無の確認を追加。

2022-06-23 07:31 UTC, Akinori13 requested changes
- .DS_StoreもGitの対象外にしてください
- pycacheもGitの対象外にしてください

2022-06-23 07:31 UTC, Akinori13 commented on accounts/tests.py
> +            self.assertTrue(session_key_confirm)
何となくやろうとしていることは分かりますが、`self.assertIn(SESSION_KEY, self.client.session)`みたいな感じで大丈夫です

2022-06-23 07:31 UTC, Akinori13 commented on tweets/views.py
> +
空行になってないです。スペースが挿入されています

2022-06-23 08:37 UTC, fujinomoto62 commented on accounts/tests.py
> +            self.assertTrue(session_key_confirm)
変更しました。

2022-06-26 01:04 UTC, Akinori13 approved these changes

2022-06-26 01:05 UTC, Akinori13 commented
LGTM

2022-06-26 01:05 UTC, merged