Create new tweets
shinonome-inc/backend-final-assignment-Fujioka_backend pull request #3
Opened 2022-06-30 10:12 UTC by fujinomoto62

This commit aims to create new tweets and their detail page.

2022-07-01 03:43 UTC, Akinori13 requested changes
良くかけています！！！！
Basic Backend 2022は参照していますか？再度確認をお願いしたいです！！！

2022-07-01 03:43 UTC, Akinori13 commented on tweets/templates/tweets/create.html
> +        </form>
エラーメッセージの表示はこの実装でできますか？

2022-07-01 03:43 UTC, Akinori13 commented on tweets/views.py
> +    fields = ('text', 'author')
authorはrequest.userから取得できるようにしてください。

2022-07-01 03:43 UTC, Akinori13 commented on tweets/models.py
> +    created_date = models.DateTimeField(null=True, blank=True, default=timezone.now)
`null=True, blank=True`にする必要ありますか

2022-07-01 03:43 UTC, Akinori13 commented on tweets/models.py
> +    author = models.CharField(max_length=50)
UserモデルとTweetモデルは1対Nの関係になります。authorは外部キーにしてください

2022-07-01 09:45 UTC, fujinomoto62 commented on tweets/templates/tweets/create.html
> +        </form>
[https://github.com/shinonome-inc/backend-final-assignment-Fujioka_backend/pull/3/commits#:~:text=Improving%20the%20safety%20of%20tweet%20authors](url)
にて、{{form}}とすることで対応しました。

2022-07-01 09:46 UTC, fujinomoto62 commented on tweets/views.py
> +    fields = ('text', 'author')
[https://github.com/shinonome-inc/backend-final-assignment-Fujioka_backend/pull/3/commits#:~:text=Improving%20the%20safety%20of%20tweet%20authors](url)
にて、post関数をオーバーライドする形で対応しました。

2022-07-01 09:54 UTC, fujinomoto62 commented on tweets/models.py
> +    author = models.CharField(max_length=50)
[Apply foreign key to tweet author]にて、対応しました。

2022-07-04 06:05 UTC, Akinori13 requested changes
数点コメントしました

2022-07-04 06:05 UTC, Akinori13 commented on tweets/views.py
> +    author = request.GET['author']
authorは偽装できます。試しにデベロッパーツールを開いて、リンクを編集して送信してみましょう。
詳細を表示するオブジェクトのauthorとrequest.userを比較してください。

2022-07-04 06:05 UTC, Akinori13 commented on tweets/views.py
> +class TweetDelete(DeleteView):
objectのauthorとrequest.userが同一でない場合は、403エラーを表示してください

2022-07-04 06:05 UTC, Akinori13 commented on tweets/views.py
> +    author = request.GET['author']
個々も他と同様に

2022-07-04 08:13 UTC, fujinomoto62 commented on tweets/views.py
> +class TweetCreate(CreateView):
Request login to create and delete tweetsにて、LoginRequiredMixinの継承より修正しました。

2022-07-04 08:14 UTC, fujinomoto62 commented on tweets/views.py
> +class TweetDelete(DeleteView):
Request login to create and delete tweetsにて、LoginRequiredMixinの継承より修正しました。
Add authentication to DeleteClassにて、UserPassesTestMixinの継承より修正しました。

2022-07-04 08:17 UTC, fujinomoto62 commented on tweets/views.py
> +    author = request.GET['author']
Request login to create and delete tweetsにて、authorをpkから取得したTweetModelから取得することで偽装を回避しました。

2022-07-04 08:17 UTC, fujinomoto62 commented on tweets/views.py
> +    author = request.GET['author']
Request login to create and delete tweetsにて、authorをpkから取得したTweetModelから取得することで偽装を回避しました。

2022-07-04 08:22 UTC, fujinomoto62 commented on tweets/views.py
> +    author = request.GET['author']
Insignificant fix(二個目)で名前で確認からUserオブジェクトの確認に変更しました。delete_confirmfuncも同様に変更しました。

2022-07-04 08:22 UTC, fujinomoto62 commented on tweets/views.py
> +    author = request.GET['author']
Insignificant fix(二個目)で名前で確認からUserオブジェクトの確認に変更しました。detailfuncも同様に変更しました。

2022-07-04 09:14 UTC, Akinori13 approved these changes

2022-07-04 09:15 UTC, merged