Like handling
shinonome-inc/backend-final-assignment-Fujioka_backend pull request #5
Opened 2022-07-09 09:18 UTC by fujinomoto62

2022-07-09 15:00 UTC, Akinori13 requested changes
いい感じです。コメントしました

2022-07-09 15:00 UTC, Akinori13 commented on tweets/views.py
> +        pass
いいねといいね取消は別のViewに分けてください

2022-07-09 15:00 UTC, Akinori13 commented on tweets/views.py
> +            liked_tweets.append(tweet.pk)
request.userがいいねしたツイートを引っ張ればもっと簡素に書けると思います
（それぞれのツイートをいいねしたユーザーの中にリクエストユーザーがいるかどうかを毎回判別するのは冗長に思います）

2022-07-09 15:00 UTC, Akinori13 commented on tweets/tests.py
UIテストは最終課題の範囲に含まれていないので、レビューはしません。

2022-07-09 15:00 UTC, Akinori13 commented on tweets/tests.py
せっかく作ってくれたのに申し訳ないですが、全ての今後のレビュアーの負担のためご理解ください

2022-07-10 04:27 UTC, fujinomoto62 commented on tweets/views.py
> +        pass
djangoの性質上、urlをトリガーとしてviewを呼び出すため、いいねといいね解除でviewを分離することは、後々処理を追加した際にいいね機能自体の予期せぬバグの原因になりかねないと判断してview は統一して作りました。
一方で、いいね作成といいね解除の処理を分離することはごもっともな意見だと存じます。
そのため、Isolate like processingにて、LikeHandleという新規Classを作成して、このClass内のプロセスにていいね作成の処理といいね解除の処理を書くことで、作成と処理のコードを分離させました。型定義など、多少雑ではありますが、動作自体は問題なく動きます。

2022-07-10 04:44 UTC, fujinomoto62 commented on tweets/views.py
> +            liked_tweets.append(tweet.pk)
それは、Userモデルに既にいいねしたツイートの情報を保持させるということでしょうか。
お言葉ですが、それではモデル間の依存関係が高まり、ドメイン駆動設計の観点からシンプルで簡潔なモデル設計とは言えないように思えます。
確かに、表示させるツイートからユーザーがいちいちいいねしたのかを判別するのは効率的な書き方とは言えません。しかし、実際にツイッターのようなサービスを運営する場合、無限スクロールなどにより表示させるツイートは限定的なものであります。更に、いいねしたのかの判別をサーバー側ではなくユーザー側の処理に任せることにより処理の負担は十分減らせると考えます。
私の解釈や考えが誤りであれば大変申し訳ありません。

2022-07-10 04:52 UTC, fujinomoto62 commented on tweets/tests.py
承知しました。
今回の設計では、いいねボタンのクリックをすべての処理のトリガーとしているため、それが正常に動作するのか確認するためにこのような方法を用いました。クリックからの処理のテストができる別の方法もいくつか試してみたのですが、正常に実行するテストが今回のseleniumしかなかったため、リメイクはご容赦ください。

2022-07-10 06:36 UTC, Akinori13 requested changes
コメントしました

2022-07-10 06:36 UTC, Akinori13 commented on tweets/tests.py
問題ないです。そのまま進めてください

2022-07-10 06:36 UTC, Akinori13 commented on tweets/views.py
> +    # POST送信の中にcsrf_tokenとtweet_pkが入っているかを確認
django.middleware.csrf.CsrfViewMiddlewareでcsrfのチェックはなされています

2022-07-10 06:36 UTC, Akinori13 commented on tweets/views.py
> +        liked = False
is_likedの方が命名として望ましいです

2022-07-10 06:36 UTC, Akinori13 commented on tweets/views.py
> +            liked_tweets.append(tweet.pk)
`liked_tweets = request.user.likemodel_set.values_list('tweet', flat=True)`

2022-07-10 06:38 UTC, Akinori13 commented on tweets/views.py
> +        pass
エンドポイントごと分けるのが想定でしたが、そのようにしたいと考えていらっしゃるならば構いません。（いいねを二回クリックしたときに、いいねを取り消しされるということなどを考慮して、エンドポイントの分離が基本でしたが）

2022-07-10 07:42 UTC, fujinomoto62 commented on tweets/views.py
> +    # POST送信の中にcsrf_tokenとtweet_pkが入っているかを確認
Fine adjustmentにてtokenの確認部分を削除しました。

2022-07-10 07:43 UTC, fujinomoto62 commented on tweets/views.py
> +        liked = False
おっしゃるとおりです。
Fine adjustmentにてlikedをis_likedに変更しました。
以後命名の際にも参考にさせていただきます。

2022-07-11 01:46 UTC, fujinomoto62 commented on tweets/views.py
> +    # POST送信の中にcsrf_tokenとtweet_pkが入っているかを確認
Fine adjustmentにて不要部分を削除しました。

2022-07-11 01:46 UTC, fujinomoto62 commented on tweets/views.py
> +        liked = False
Fine adjustmentにて変更しました。

2022-07-11 14:18 UTC, Akinori13 requested changes
いくつかコメントしました

2022-07-11 14:18 UTC, Akinori13 commented on tweets/tests.py
> +class TestFavoriteView(StaticLiveServerTestCase):
seleniumに加えて通常のテストを書いてください

2022-07-12 00:26 UTC, fujinomoto62 commented on tweets/views.py
> +        pass
ここのelseは異常状態の場合ではなく、list.htmlやdetail.htmlのGETで毎回呼び出されるものですので、現時点での何かしらのレスポンスは不要かと存じます。

2022-07-12 00:35 UTC, fujinomoto62 commented on tweets/views.py
> +def likefunc(request):
pythonは普段あまり使わず失念しておりました。
以後そのようにします。

2022-07-12 01:05 UTC, fujinomoto62 commented on tweets/views.py
> +    if request.method == 'POST' and request.POST.get('tweet_pk'):
将来性的にエラーハンドリングをするときのために分けておきました。
大変簡素ではありますが、POSTのajaxの内容物に不足があったときのみprintにて表示するようにしておきました。

2022-07-12 01:06 UTC, fujinomoto62 commented on tweets/tests.py
> +class TestFavoriteView(StaticLiveServerTestCase):
擬似的にPOSTを送信した際の挙動を確認するテストを作成しました。

2022-07-14 06:41 UTC, Akinori13 requested changes
少しコメントしました！

2022-07-14 06:41 UTC, Akinori13 commented on tweets/tests.py
> +class TestFavoriteView(StaticLiveServerTestCase):
どこに記載しましたでしょうか？見落としているかもしれないので行番号を教えてください！

2022-07-14 06:41 UTC, Akinori13 commented on tweets/views.py
> +        pass
> list.htmlやdetail.htmlのGETで毎回呼び出されるもの

とはどのような意味合いでしょうか。(ブラウザの先読み機能のことをおっしゃっていますか？)
list.htmlやdetail.htmlでは、"ボタンクリック時"に当該ViewのエンドポイントにPOST送信されると思います！

確かにreturnする必要はありませんが、適切なHTTPメソッドを用いているかの配慮はあってもいいかと思います。場合によってはelse以下を消しても問題ないです。ここは最終課題ではさほど気にするべき点でもありませんので、そのままでもよいです

2022-07-14 07:56 UTC, fujinomoto62 commented on tweets/tests.py
> +class TestFavoriteView(StaticLiveServerTestCase):
追加したテスト内容と場所は以下の通りです。
（commit: 7/11 Comment correction）tweets/test.py 
166~168：存在するツイートに対してPOST送信を行い、LikeModelが作成されるか確認しました。
181~182：存在しないツイートに対してPOST送信を行い、LikeModelが作成されていないことを確認しました。
199~210：LikeModelが存在するツイートに対してPOST送信を行い、LikeModelが削除されるか確認しました。

2022-07-14 08:03 UTC, fujinomoto62 commented on tweets/views.py
> +        pass
like.htmlはlist.htmlやdetail.htmlにincludeされており、これらのページがgetされるのに伴ってlike.htmlもgetさるという認識です。（私の理解が誤りでしたら申し訳ありません）
おっしゃるとおり、今回の場合はGETでの処理が無い限りelse自体を書くべきではありませんでした。

2022-07-15 16:33 UTC, Akinori13 requested changes
1点コメントしました

2022-07-16 03:42 UTC, fujinomoto62 commented on tweets/tests.py
> +        self.assertTrue(LikeModel.objects.exists())
[commit: separete test]にて分離しました。

2022-07-17 05:45 UTC, Akinori13 commented on tweets/views.py
> +        pass
こちらのコメントを返すのを忘れていました。ごめんなさい。
like.htmlはlist.htmlやdetail.htmlにincludeされますが、それはlike.htmlをGETすることを意味しません。あくまでもlist.htmlのincludeで、likefuncへのGETリクエストではありません。そもそもlike.htmlをGETするという表現自体が認識に誤りがあると感じます。（動的サーバーと静的サーバーの違いを学習すると助けになるかもしれません。）

2022-07-17 05:45 UTC, merged

2022-07-17 07:43 UTC, fujinomoto62 commented on tweets/views.py
> +        pass
承知しました。
incloud元のファイルがGETされてもinclude先のファイルにGETされないのは私の勘違いでした。Reactとの理解が混同しておりました。
以後作り時に気をつけます。勉強になりました。