Followee handling
shinonome-inc/backend-final-assignment-Fujioka_backend pull request #6
Opened 2022-07-17 16:01 UTC by fujinomoto62

2022-07-18 08:20 UTC, fujinomoto62 reviewed
コメントテスト

2022-07-18 08:34 UTC, fujinomoto62 reviewed
[(extra edit) expand the range of like button fill]
本PRとは関係ないコード改善です。
ツイート詳細画面とプロフィール画面にて、押されたいいねボタンが♡となっていたので、♥となるようにしました。

2022-07-18 08:38 UTC, fujinomoto62 reviewed
[create following json response]
フォロー処理をFetch APIにより作成しました。
動作原理はいいねのときとほぼ一緒です。
followfuncにてJSより送られたPOST送信を受理し、データベースの操作を行います。
この時点でフォロー機能は完成です。
また、viewの一部修正を行っています。

2022-07-18 08:40 UTC, fujinomoto62 reviewed
[(extra edit) add like data type]
本PRとは関係ないコード改善です。
いいねボタンの処理において、タイプ指定していたものを書き忘れていたので、一応修正しました。型を定義しただけですので、動作については一切替わりません。

2022-07-18 08:41 UTC, fujinomoto62 reviewed
[show following/er number]
フォロワーとフォロイーの人数を表示しました。

2022-07-18 08:42 UTC, fujinomoto62 reviewed
[create following test]
フォロー関係のテストをを追加しました。
今回はUI関連のテストは記載しておりません。

2022-07-18 08:47 UTC, fujinomoto62 reviewed
[Fixed processing when inappropriate POST content]
UI上ではできませんが、POST送信で自分自身をフォローすることができたため修正しました。
また、Likeにおいても似たような修正をしました。
どちらもエラーハンドリングの際に特別な内容物を入れてJsonResponseを返すことで、エラー感知を容易たらしめると思います。

2022-07-18 08:48 UTC, fujinomoto62 reviewed
[create profile link in header]
隠していたヘッダーのプロフィールリンクを再度出現させました。

2022-07-19 09:43 UTC, Akinori13 requested changes
いい感じです。いくつかコメントしました

2022-07-19 09:43 UTC, Akinori13 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
`null=False`は必要ですか

2022-07-19 09:43 UTC, Akinori13 commented on accounts/urls.py
> +    path('follow', followfunc, name='follow'),
どちらに統一するかは置いときまして、
```suggestion
    path('follow/', followfunc, name='follow'),

```

2022-07-19 09:43 UTC, Akinori13 commented on accounts/views.py
> +    identity = True if client_user == account else False
命名をもう少し分かりやすくしましょう。またboolはis_~で命名してください。

2022-07-19 09:43 UTC, Akinori13 commented on accounts/views.py
> +    if (identity == False) :
```suggestion
    if (!identity) :
```

2022-07-19 09:43 UTC, Akinori13 commented on accounts/views.py
> +    tweets_exist = True if user_tweets else False
filter使うのはだめですか

2022-07-19 09:43 UTC, Akinori13 commented on accounts/views.py
> +            follow_detecting = True if account.pk in client.following_user.values_list('follower_user', flat=True) else False
命名

2022-07-19 13:27 UTC, fujinomoto62 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
データの安全性を確保するために必要だと考えました。
フォロー再現の方法上、following_userとfollower_userは必ず同時に登録する必要があります。万が一どちらか一方だけ登録してしまうと、フォロワーやフォロイーの数の辻褄が合わなくなる他、そのような誤ったデータを適切な形に直すことは困難になります。これらのような潜在的な問題が発生しないよう、`null=False`は必要だと考えました。

2022-07-19 14:26 UTC, fujinomoto62 commented on accounts/urls.py
> +    path('follow', followfunc, name='follow'),
[Change variable names and add dynamic count styles]にて修正しました。

2022-07-19 14:27 UTC, fujinomoto62 commented on accounts/views.py
> +    identity = True if client_user == account else False
[Change variable names and add dynamic count styles]にて個人的にわかりやすかろう名前に修正しました。

2022-07-19 14:35 UTC, fujinomoto62 reviewed
7/19のコメントの修正しました。
また、フォローボタンを押したときにが画面上のフォロワー数とフォローボタンの文字の動的変化を忘れていたため追加しました。

2022-07-21 11:20 UTC, Akinori13 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
Djangoはデフォルトで`null=False`です。

2022-07-21 11:30 UTC, Akinori13 commented on accounts/views.py
> +    if (identity == False) :
javascriptでした!!!!!（すみません）
以下でできるはずです
```
if not is_same_user:
```

2022-07-21 12:07 UTC, Akinori13 requested changes
いくつか
- アンフォローのテスト追加
- フォロワー一覧の画面作成
- フォロー一覧の画面作成

2022-07-21 12:07 UTC, Akinori13 commented on accounts/tests.py
>      def test_success_post(self):
ステータスコードの確認をお願いします（すべて）

2022-07-21 12:07 UTC, Akinori13 commented on accounts/views.py
> +            client = get_object_or_404(User, pk=body['client_pk'])
client_pkを送信してもらう必要性事態を再検討していていただきたいです

2022-07-21 12:07 UTC, Akinori13 commented on accounts/views.py
> +from django.shortcuts import get_list_or_404, get_object_or_404, render
不要なimportはありませんか

2022-07-22 06:29 UTC, fujinomoto62 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
related_nameに関しては、各FollowModelのfollowing_user, follower_userに含まれるユーザー数は1人であるためと、データ名と統一するためにこのようにしています。

2022-07-22 06:29 UTC, fujinomoto62 commented on accounts/templates/accounts/script.html
> +  // いいねボタンのスタイルを変更
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
いいねボタン→フォローボタン

2022-07-22 06:29 UTC, fujinomoto62 commented on accounts/views.py
> +    clicked_account = get_object_or_404(User, pk=user_pk)
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
clicked_account→profile_user

2022-07-22 06:30 UTC, fujinomoto62 commented on accounts/views.py
> +    is_same_user: bool = True if client_user == clicked_account else False
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
勉強になります。

2022-07-22 06:30 UTC, fujinomoto62 commented on accounts/views.py
> +        follow_detecting = True if clicked_account.pk in client_user.following_user.values_list('follower_user', flat=True) else False
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
勉強になります。

2022-07-22 06:31 UTC, fujinomoto62 commented on accounts/views.py
> +def profilefunc(request, user_pk):
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
これを機にすべての関数名をpythonの慣習に習い_funcと変更しました。

2022-07-22 06:32 UTC, fujinomoto62 commented on accounts/views.py
> +def followfunc(request):
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
これを機にすべての関数名をpythonの慣習に習い_funcと変更しました。

2022-07-22 06:33 UTC, fujinomoto62 commented on accounts/views.py
> +            client = get_object_or_404(User, pk=body['client_pk'])
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。
操作ユーザの情報はrequest経由で取得に変更しました。

2022-07-22 06:33 UTC, fujinomoto62 commented on accounts/tests.py
>      def test_success_post(self):
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。

2022-07-22 06:33 UTC, fujinomoto62 commented on accounts/views.py
> +from django.shortcuts import get_list_or_404, get_object_or_404, render
[add following/er page and fixed code (cmnt: 7/22)]にて修正しました。

2022-07-22 06:37 UTC, fujinomoto62 commented on accounts/views.py
> +    if (identity == False) :
僕もJSと勘違いしておりました。
not boolではboolの反転であるため意図した動作にはなりません。ですが、該当箇所は修正して一新されましたのでとりあえず解決しました。

2022-07-22 06:48 UTC, fujinomoto62 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
そうなのですか。勉強になります。
確かにデフォルトで`null=False`なら書く必要はないです。ですが、これはあくまで僕の主観によるものですが、致命的な欠陥を防ぐためのコードを明示的に記入しておくことは安全性の向上や仕様変更時の対策につながるためこのままでも良い気がします。（TypeScriptで明示的に : void とするときのような感じといいましょうか。）

2022-07-23 10:10 UTC, Akinori13 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
そのようにしたいのであればそれで構いません。なお案件ではそういった方針ではないですし、有名なDjango製OSSでもそのような方針にはなっていないです。

2022-07-23 10:20 UTC, Akinori13 commented on accounts/views.py
> +def profilefunc(request, user_pk):
そういった慣習は初めて知りました！そういえば僕も一時期ハンガリアン記法みたいなのを使ってました
ちなみに案件ではそういった命名規則には基本的にはしないですし、たいていのpythonのライブラリでもそういった命名は見かけないです

2022-07-23 10:42 UTC, Akinori13 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
修正は複合ユニークではないと思います。複合ユニークはUserAとUserBというセットがユニークであるということです。これではUserAがUserBをフォローした後に、UserCをフォローすることができないと思いますが、そうではないですか？

それからrelated_nameに関しては逆参照をもう一度チェックすると良いと思います。若干理解できていないのではと感じます。命名は難しいですからそのままでも問題ないです。デフォルトだとfollow_model_setみたいな感じだと思うので、一般的には複数形だと思います。

2022-07-23 12:42 UTC, fujinomoto62 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
複合ユニークについては[create unique constraint]にて修正しました。これにて同じフォロワーとフォロイーの組み合わせでの登録ができなくなったと思います。

>>デフォルトだとfollow_model_setみたいな感じだと思うので、一般的には複数形だと思います。
申し訳ありませんが意味がわかりかねます。私のrelated_nameの使い方になにかおかしな点があったでしょうか。

2022-07-23 13:04 UTC, fujinomoto62 commented on accounts/views.py
> +    client_user = request.user
[change client user name]にて修正しました。

2022-07-23 13:04 UTC, fujinomoto62 commented on accounts/views.py
> +    tweets_exist = True if user_tweets else False
[change client user name]にて修正しました。

2022-07-23 16:12 UTC, Akinori13 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
ちょっと説明が雑であったことは申し訳ないです。そうですね、ここは難しいですが、すっきりとした命名ではないように感じます。

逆参照の基礎は理解している前提です（[これ](https://djangobrothers.com/blogs/related_name/)は参考になるかもしれないです）

そもそも単に逆参照をしたければ、`request.user.followmodel_set.all()`で十分です。

でもfollowmodel_setは混乱してしまいます。followmodel_set.all()は以下の2つの意味をもちます
1. `FollowModel.objects.filter(following_user=request.user)`
2. `FollowModel.objects.filter(follower_user=request.user)`

どちらでしょうか。区別できませんね。区別するためにrelated_nameを用いるわけです。

さてrelated_nameをxとしたとき、これはobjectsやfollowmodel_setにあたるものですから複数の意味を持つ命名が望ましいようにおもっております。さらにfollowmodelのオブジェクトを返しますからfollowmodelとfollowing_user（あるいはfollower_user）の意味を重ねた命名がよいと思います。

さしあたりこのように記載しましたが、実際には個別の状況により命名は異なるでしょう（さきほどの上のコメントは適切ではありませんでした。ベストプラクティスがあるか探したり聞いてみたりしてみます。）。命名はこのままで構いませんが、このような理解の上で取り組んでいただますと嬉しいです。

【さらに個人の意見。無視して大丈夫です】
objectsや~_setは実際にはManagerです。Djangoがなぜこのような命名にしているのか自分にはいまいち分かっていないのが現状で、もう少し深めて知りたいです

2022-07-25 00:52 UTC, Akinori13 commented on accounts/views.py
> +    tweets_exist = user_tweets.exists()
命名

2022-07-25 02:31 UTC, fujinomoto62 commented on accounts/models.py
> +    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='follower_user')
はい、基本的な逆参照の理解その使用方法と、related_nameの使用意義については理解しているつもりです。
本件においても、ForeignKeyをもつフィールドが複数あったため逆参照のためにrelated_nameをつけました。

命名については理解しました。今回はrelated_nameとフィールド名が異なっていると使いにくいかと思い、related_nameの名前はそのフィールド名と同じものにしました。以後、命名の際はおっしゃられたことに留意して命名します。

2022-07-25 02:35 UTC, fujinomoto62 commented on accounts/views.py
> +    tweets_exist = user_tweets.exists()
[change tweets_exist name]にて修正しました。
tweets_exist → is_tweets_exist

2022-07-25 02:37 UTC, fujinomoto62 commented on accounts/views.py
> +def profilefunc(request, user_pk):
djangoのライブラリでこのような命名を見かけたような気がしたので、このようにしましたが、私の勘違いであったかもしれません。すみません。

2022-07-26 08:37 UTC, Akinori13 commented
LGTM

2022-07-26 08:37 UTC, merged